@test("four test")
def fourTest():
    raise Exception("four test")
